name: PLAID Service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Get the timestamp for tagging
        id: get_time
        run: echo "TAG=$(date +'%d%m.%H%M')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/bits-bank-plaid:${{ env.TAG }}
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - 
        name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name bits-bank-cluster --region ap-south-1
      - 
        name: Deploy to EKS
        run: |
          kubectl set image statefulset/bits-auth-svc bits-auth-svc=${{ vars.DOCKERHUB_USERNAME }}/bits-bank-auth:${{ env.TAG }} -n default
